## C++ Basics

In this lesson, the basic syntax of C++ is introduced with parallels drawn to analogous features of `Python` as is needed.  In order to run this worksheet, you must install `xeus-cling` via

```
conda install xeus-cling -c conda-forge
```

This installs a `C++` interpreter (i.e., something that can chomp on C++ code on-the-fly like Python) and an associated kernel for use in Jupyter.  This is *not* the way to use C++ in practice, but I'll use it for introducing syntax, short use cases, and comparisons to Python. 

For compiling code later in the lesson, you'll need to install `g++` via

```
sudo apt install g++
```


My philosophy for this and the next several lessons is to *teach programmers how to program in C++*.  The catch is that you've got to be solid with Python (or something else) already!

## Required Preparation

 - Read Chapters 1--7 of Allen Downey, *Think C++*; it's available for free [online](http://greenteapress.com/thinkcpp/thinkCScpp.pdf).  
 - Install `xeus-cling` and `g++`
 - Run at least the next cell before class and inform Prof. Roberts of any issues via `#lecture` channel on Slack.

In [19]:
#include <iostream>
int a = 123;
double b = 3.14;
std::cout << "Hello, world!  By the way, a = " << a << " and b = " << b << std::endl;

Hello, world!  By the way, a = 123 and b = 3.14


The output should be 
```
Hello, world!  By the way, a = 123 and b = 3.14
```

## Objectives

- Define variables of basic types
- Use basic variables with arithmetic and other operations
- Apply selection (`if`'s) and iteration (`while` and `for`)
- Write, compile, and execute first C++ program

## Declaring and Initializing Variables

C++ is *statically* typed, unlike Python, which is *dynamically typed*.  That means, in Python, one can do this with no problem:

```python
i = 123 # a is first defined and assigned an integer value
i = 1.23 # a is reassigned a float value
```

No so in C++, which requires one *declare the type*.  The built-in types are similar to those in Python and include `int`, `float`, `bool`, `char`, `double`, and `unsigned`.  In addition, a variable can be declared as `const` (making it "immutable").

In [ ]:
// int and unsigned


In [ ]:
// float and double


In [ ]:
#include <cstdio>
std::printf("%.16f %.16f", f, d); // too bad does not work in Jupyter :(
std::cout << f << " and " << d << std::endl;
std::cout.precision(17);
std::cout << f << " and " << d << std::endl;

In [ ]:
// bool


In [2]:
// char
char letter = 'h';
letter

'h'

In [9]:
char word[] = "hello";
word

input_line_23:2:7: error: redefinition of 'word'
 char word[] = "hello";
      ^
input_line_13:2:7: note: previous definition is here
 char word[] = "hello";
      ^


Interpreter Error: 

In [12]:
#include <string> // easier than char arrays!

## Operators

The normal arithmetic operations include:

```c++
x+y // plus
+x  // unary plus
x*y // multiply
x/y // divide
x%y // remainder (for integers)
```

Comparison operators include:

```c++
x==y // equality
x!=y // not equal
x>y  // greater than
x>=y // greater than or equal
```

Logical operators include:

```c++
x&y  // bitwise and
x|y  // bitwise or
x^y  // bitwise exclusive or
x&&y // logical and
x||y // logical or
```

1

## Conditionals

```c++
if (condition)
{
   // one or more statements   
}
else if (condition)
{
   // one or more statements     
}
else
{
   // one or more statements     
}
```

In [17]:
int x;         // write a quick program to 
bool is_even;  // decide whether x is even

In [43]:
x = 2;
// your program here.  make sure to set is_even.

2

## Simple Loops

```c++
while (condition)
{
    // do something.  
    if (some other condition) break;   
}
```

In [46]:
// use a while loop to add the integers 1 through n, and name the result sum.
int n;

input_line_71:3:5: error: redefinition of 'n'
int n;
    ^
input_line_69:3:5: note: previous definition is here
int n;
    ^


Interpreter Error: 

In [45]:
n = 10;

In [47]:
// your code here

The same thing but with a `for` loop:

In [49]:
sum = 0;
for (int i = 1; i <= n; i++)
{
    sum = sum + i;
}
sum

55

## A First Program

Copy and paste the following lines of code into a file named `hello_world.cc`:

```c++
#include <iostream>

int main(int argc, char* argv[])
{
  std::cout << "Hello, world!" << std::endl;
  return 0;
}
```

Go to the command line and execute:

```bash
g++ -o hello_world hello_world.cc
```